baseurl = "https://example.org/"
languageCode = "en-us"
title = "Everything about Doc Dayao"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
# disqusShortname = "spf13"
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"

[params]
    site_author = "Doc Dayao"
    site_description = "Doc Dayao Blog Site"
    location = "Earth"
    # Link custom assets relative to /static
    avatar = "img/docdayao170x167.jpg"
    header_background = "img/banner1920x577.JPG"
    header_title = "Life is a dialogue."
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Define which content types are shown on the homepage
    mainSections = ["post"]

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "docdayao"
    facebook  = "jonathan.dayao1"
    linkedin  = "dayao"
    behance   = ""
    dribbble  = ""
    instagram = "docdayao"
    github    = "docdayao"
    gplus     = ""
